### ISSUE TITLE
Kneaddata install and use

### ISSUE THREAD

**Issue by BrandonBerryhill** [michaelwoodworth/practicalmetagenomics#4]
Hi Michael,

Josh and I are having issues getting Kneaddata to install and run. Would we be able to run through the install and its useage? In particular: i) how to add things to $PATH, ii) managing dependencies (such as installing the right versions of the tools needed when doing the pip install here http://huttenhower.sph.harvard.edu/kneaddata), iii) the choice of bowtie2 versus BMTagger.

Thanks,
Brandon

**Comment by michaelwoodworth** [comment]
Hi Josh and Brandon.

Here are some responses to these questions:

i) working with the `$PATH` can get clunky pretty fast. the short answer is that directories can be added to your path with the following command (where `${new_directory_of_interest}` represents your directory or variable that contains the new directory path):

`export PATH="$PATH:${new_directory_of_interest}"`

The longer answer is that the `$PATH` variable is an environmental variable, which is a list of directories that the shell will use to look for files when you don't provide a full path. It provides an prioritized order of directories as ":" colon separated list for the shell to look through.

`echo $PATH` will tell you what directories are currently in your path if you want to start there.

ii) we can spend some time on 2/10/23 talking about managing dependencies. I haven't seen many better practices for this other than creating new conda environments with each new installation and avoiding installing stuff in your base environment. I would be interested in what others in the group have seen/done as well. In the example you are highlighting, pip is another package manager that works a lot like conda, just without the swanky layer of having separate environments. So if you need to install a tool and make sure it has all the dependencies, pip will also work. You can imagine that it takes a fair amount of work to maintain conda, pip, docker images etc. with each new version of software, so some developers may only maintain a subset of the most popular tools.

I outlined some of the steps for setting up kneaddata but was unable to test all of this code but have added another section to the [quality control GitHub page](https://github.com/michaelwoodworth/practicalmetagenomics/blob/main/pages/23.02.03.md#kneaddata-for-trimmomatic-and-host-read-removal) on host read decontamination that may help a bit.

iii) we can also talk about this briefly on 2/10/23. Bowtie2 is much more straightforward to use and bowtie2 is one of the most widely used read mappers as it is very fast and computationally efficient. I can't remember seeing a direct comparison of human read removal with both tools. I was first taught to use bmtagger but am starting to use bowtie2 since it is better maintained as a tool and easier to use. I can try to show you tomorrow that it doesn't always remove all human reads though.

**Comment by michaelwoodworth** [comment]
I'm going to mark this as closed but please reopen if I missed something!
